name: Run clang-format Linter

on:
  pull_request:
  push:
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main


jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        exclude: './subprojects'
        extensions: 'h,c'
        clangFormatVersion: 12
        inplace: True
